{{- range .Values.deployments }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
  labels:
    app: '{{ $.Values.global.labelPrefix }}-{{ $.Values.global.env }}-{{ .label }}-service'
  name: '{{ $.Values.global.labelPrefix }}-{{ $.Values.global.env }}-{{ .label }}-service'
  namespace: '{{ $.Values.global.namespace }}'
spec:
  endpoints:
    - port: http-metrics
      scheme: http
      path: /prometheus
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_label_app]
          targetLabel: instance
  selector:
    matchLabels:
      app: '{{ $.Values.global.labelPrefix }}-{{ $.Values.global.env }}-{{ .label }}-service'
  namespaceSelector:
    matchNames:
      - {{ $.Values.global.namespace }}
{{- end }}      
