{
 "title": "Harbor Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Repositories",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(harbor_repositories_tags_total) by (repo_name) "
    },
    {
     "expr": "sum(harbor_repositories_pull_total) by (repo_name) "
    },
    {
     "expr": "sum(harbor_repositories_star_total) by (repo_name) "
    }
   ]
  },
  {
   "title": "Storage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum (harbor_quotas_size_bytes{type=\"used\"}) by (repo_name)",
     "legendFormat": "{{repo_name}}"
    }
   ]
  },
  {
   "title": "repo count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 10, "y": 6 },
   "targets": [
    {
     "expr": "sum (harbor_quotas_count_total{type=\"used\"}) by (repo_name)",
     "legendFormat": "{{repo_name}}"
    }
   ]
  }
 ]
}