{{- range .Values.deployments }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: >-
    {{ $.Values.global.labelPrefix }}-{{ $.Values.global.env }}-{{ .label  }}-sa
  namespace: {{ $.Values.global.namespace }}
{{- end }}  